services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./src:/app
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        environment:
            POSTGRES_DB: recipe
            POSTGRES_USER: sonya
            POSTGRES_PASSWORD: sonya
            POSTGRES_HOST: db
            SECRET_KEY: "test"
        depends_on:
            - db
        networks:
            - app-network
    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: recipe
            POSTGRES_USER: sonya
            POSTGRES_PASSWORD: sonya
        ports:
            - "5432:5432"
        networks:
            - app-network
        volumes:
            - ${PWD}/postgres_data:/var/lib/postgresql/data
networks:
    app-network:
        driver: bridge
volumes:
    postgres_data: