name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install Dependencies
      run: poetry install --no-root
    - name: Wait for Database
      run: |
        while ! nc -z db 5432; do
          sleep 1
        done
    - name: Run Migrations
      run: poetry run python src/manage.py migrate
    - name: Run Test for core app
      run: poetry run python src/manage.py test core
    - name: Run Test for user app
      run: poetry run python src/manage.py test user
