name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: recipe
          POSTGRES_USER: sonya
          POSTGRES_PASSWORD: sonya
          POSTGRES_HOST: db
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install Dependencies
      run: "poetry install --sync"
    - name: Create a directory for static files
      run: "mkdir -p /vol/web/static && mkdir -p /vol/web/media"
    - name: Change ownership of the directory
      run: "chown -R sonya:sonya /vol"
    - name: Change permissions of the directory
      run: "chmod -R 755 /vol/web"
    - name: Wait for PostgreSQL to be ready
      run: "sleep 10"
    - name: Run Tests
      env:
        SECRET_KEY: "test"
        DATABASE_URL: "postgres://sonya:sonya@db:5432/recipe"
      run: |
      poetry run python src/manage.py test core
      poetry run python src/manage.py test user
      poetry run python src/manage.py test recipe
