name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: recipe
          POSTGRES_USER: sonya
          POSTGRES_PASSWORD: sonya
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install Dependencies
      run: poetry install --no-root
    - name: Run Test for core app
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: poetry run python manage.py test core
    - name: Run Test for user app
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: poetry run python manage.py test user
